"""test5

Revision ID: 136ec950a3ee
Revises: ceab834ca692
Create Date: 2022-02-01 18:28:54.602826

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.


revision = '136ec950a3ee'
down_revision = 'ceab834ca692'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('banner', 'title',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('banner', 'status',
               existing_type=postgresql.ENUM('Enabled', 'Disabled', name='status'),
               nullable=False,
               server_default="Disabled")
    op.drop_constraint('uq_banner_title', 'banner', type_='unique')
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_banner_title', 'banner', ['title'])
    op.alter_column('banner', 'status',
               existing_type=postgresql.ENUM('Enabled', 'Disabled', name='status'),
               nullable=True)
    op.alter_column('banner', 'title',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    # ### end Alembic commands ###
