"""init

Revision ID: 4668eca463bf
Revises: 0889b679f676
Create Date: 2022-01-19 14:04:21.770346

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4668eca463bf'
down_revision = '0889b679f676'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
