"""init

Revision ID: 886c1fa876b4
Revises: 
Create Date: 2022-01-18 16:16:28.898370

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '886c1fa876b4'
down_revision = None
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
