"""init

Revision ID: 0889b679f676
Revises: 886c1fa876b4
Create Date: 2022-01-19 14:01:02.220906

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0889b679f676'
down_revision = '886c1fa876b4'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
