import sqlalchemy
from paginate_sqlalchemy import SqlalchemyOrmPage
from ..models.banner import Banner


class BannerRecordService(object):

    @classmethod
    def get_paginator(cls, request, query, size, page=1):
        query_params = request.GET.mixed()
        items_per_page = size

        def url_maker(link_page):
            # replace page param with values generated by paginator
            query_params['page'] = link_page
            return request.current_route_url(_query=query_params)
        return SqlalchemyOrmPage(query, page, items_per_page, url_maker=url_maker)
